/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.edd;

/**
 *
 * @author derek
 */
public class InterfazGrafica extends javax.swing.JFrame {
    
    private GestorInvestigaciones gestor;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.gestor = new GestorInvestigaciones();
        this.setLocationRelativeTo(null);
        this.gestor = GestorInvestigaciones.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        bntBuscarAutor = new javax.swing.JButton();
        btnBuscarPalabraClave = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargar.setText("Cargar Resumen");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnAnalizar.setText("Analizar Resumen");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        bntBuscarAutor.setText("Buscar por Autor");
        bntBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(bntBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnBuscarPalabraClave.setText("Buscar por Palabra Clave");
        btnBuscarPalabraClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPalabraClaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnListar.setText("Listar Palabras Clave");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnEliminar.setText("Eliminar un Resumen");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 470, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int seleccion = fileChooser.showOpenDialog(this);

    if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        try {
            // Lógica de lectura del archivo (Parsing)
            java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo));
            String linea;
            String titulo = "";
            ListaSimple<String> autores = new ListaSimple<>();
            String cuerpo = "";
            ListaSimple<String> palabrasClave = new ListaSimple<>();
            
            // Banderas para saber qué parte estamos leyendo
            boolean leyendoAutores = false;
            boolean leyendoResumen = false;
            boolean leyendoPalabras = false;
            StringBuilder sbCuerpo = new StringBuilder();

            while ((linea = br.readLine()) != null) {
                linea = linea.trim();
                if (linea.isEmpty()) continue;

                if (titulo.isEmpty()) {
                    titulo = linea; // La primera línea no vacía es el título
                } else if (linea.equals("Autores")) {
                    leyendoAutores = true;
                    leyendoResumen = false;
                    leyendoPalabras = false;
                } else if (linea.equals("Resumen")) {
                    leyendoAutores = false;
                    leyendoResumen = true;
                    leyendoPalabras = false;
                } else if (linea.startsWith("Palabras claves:")) { // Ajustar según el formato exacto del txt
                    leyendoAutores = false;
                    leyendoResumen = false;
                    leyendoPalabras = true;
                    // A veces las palabras están en la misma linea
                    String[] parts = linea.replace("Palabras claves:", "").split(",");
                    for(String p : parts) palabrasClave.agregar(p.trim());
                } else {
                    // Llenado de datos según la bandera activa
                    if (leyendoAutores) {
                        // Separar autores si vienen en una linea o varias
                        String[] autoresLinea = linea.split(","); // O salto de linea
                        for(String a : autoresLinea) autores.agregar(a.trim());
                    } else if (leyendoResumen) {
                        sbCuerpo.append(linea).append(" ");
                    } else if (leyendoPalabras) {
                        // Si las palabras vienen debajo
                        String[] keys = linea.split(",");
                        for(String k : keys) palabrasClave.agregar(k.trim());
                    }
                }
            }
            br.close();
            cuerpo = sbCuerpo.toString();

            // CREAR Y GUARDAR EL RESUMEN
            Resumen nuevoResumen = new Resumen(titulo, autores, cuerpo, palabrasClave);
            gestor.agregarResumen(nuevoResumen);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Resumen cargado exitosamente:\n" + titulo);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void bntBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarAutorActionPerformed
        // TODO add your handling code here:
        String autor = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del autor:");
    
    if (autor != null && !autor.isEmpty()) {
        ListaSimple<Resumen> resultados = gestor.buscarResumenesPorAutor(autor);
        
        txtAreaResultados.setText(""); 
        txtAreaResultados.append("--- INVESTIGACIONES DE: " + autor + " ---\n\n");
        
        if (resultados != null && resultados.getTamano() > 0) {
            for (int i = 0; i < resultados.getTamano(); i++) {
                Resumen r = resultados.get(i);
                txtAreaResultados.append("• " + r.getTitulo() + "\n");
            }
        } else {
            txtAreaResultados.append("Este autor no tiene investigaciones registradas.");
        }
    }
        
    }//GEN-LAST:event_bntBuscarAutorActionPerformed

    private void btnBuscarPalabraClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPalabraClaveActionPerformed
        // TODO add your handling code here:
        String palabra = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la palabra clave a buscar:");
    
    if (palabra != null && !palabra.isEmpty()) {
        ListaSimple<Resumen> resultados = gestor.buscarResumenPorPalabra(palabra);
        
        txtAreaResultados.setText(""); // Limpiar pantalla
        txtAreaResultados.append("--- RESULTADOS PARA: " + palabra + " ---\n\n");
        
        if (resultados != null && resultados.getTamano() > 0) {
            for (int i = 0; i < resultados.getTamano(); i++) {
                Resumen r = resultados.get(i);
                txtAreaResultados.append("Título: " + r.getTitulo() + "\n");
                txtAreaResultados.append("Autores: ");
                // Recorrer autores para imprimir
                for(int j=0; j<r.getAutores().getTamano(); j++){
                     txtAreaResultados.append(r.getAutores().get(j) + "; ");
                }
                txtAreaResultados.append("\n--------------------------\n");
            }
        } else {
            txtAreaResultados.append("No se encontraron investigaciones con esa palabra.");
        }
    }
        
    }//GEN-LAST:event_btnBuscarPalabraClaveActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        // 1. Preguntar si está seguro (Opcional, pero se ve profesional)
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Desea guardar los cambios antes de salir?", 
            "Salir", 
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION
    );

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Guardar los datos
        gestor.guardarDatos();
        javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados. ¡Hasta luego!");
        System.exit(0);
        
    } else if (confirmacion == javax.swing.JOptionPane.NO_OPTION) {
        // Salir sin guardar
        System.exit(0);
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        ListaSimple<String> titulos = gestor.obtenerTitulosDisponibles();
    
    if (titulos.getTamano() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay resúmenes cargados.");
        return;
    }

    // Convertir lista propia a Array para el JComboBox
    String[] opciones = new String[titulos.getTamano()];
    for(int i=0; i<titulos.getTamano(); i++) opciones[i] = titulos.get(i);

    String seleccionado = (String) javax.swing.JOptionPane.showInputDialog(
        this, "Seleccione resumen:", "Analizar", 
        javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

    if (seleccionado != null) {
        txtAreaResultados.setText(gestor.obtenerDetallesResumen(seleccionado));
    }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ListaSimple<String> titulos = gestor.obtenerTitulosDisponibles();
    
    if (titulos.getTamano() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nada que eliminar.");
        return;
    }

    String[] opciones = new String[titulos.getTamano()];
    for(int i=0; i<titulos.getTamano(); i++) opciones[i] = titulos.get(i);

    String seleccionado = (String) javax.swing.JOptionPane.showInputDialog(
        this, "ELIMINAR RESUMEN:", "Cuidado", 
        javax.swing.JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);

    if (seleccionado != null) {
        if (gestor.eliminarResumenGlobal(seleccionado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Eliminado correctamente.");
            txtAreaResultados.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        // 1. Llamamos al gestor para que nos de el texto listo
    String reporte = gestor.generarListadoPalabras();
    
    // 2. Limpiamos el área de texto antes de mostrar
    txtAreaResultados.setText("");
    
    // 3. Mostramos el reporte
    txtAreaResultados.append(reporte);
    
    // (Opcional) Movemos el cursor al inicio por si el texto es muy largo
    txtAreaResultados.setCaretPosition(0);
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscarAutor;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnBuscarPalabraClave;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaResultados;
    // End of variables declaration//GEN-END:variables
}
